#!/usr/bin/env bash
# Knowledge Hub — One-Click Install Script
# Designed for AI agents: zero human interaction required
# Usage: bash install.sh [--port 10128] [--admin-token xxx]

set -e

PORT=10128
ADMIN_TOKEN=""
HUB_DIR="$(cd "$(dirname "$0")" && pwd)"

# ─── Color helpers ───
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log()  { echo -e "${GREEN}[KB-Hub]${NC} $1"; }
warn() { echo -e "${YELLOW}[KB-Hub]${NC} $1"; }
err()  { echo -e "${RED}[KB-Hub]${NC} $1"; }

# ─── Parse args ───
while [[ $# -gt 0 ]]; do
  case $1 in
    --port) PORT="$2"; shift 2 ;;
    --admin-token) ADMIN_TOKEN="$2"; shift 2 ;;
    *) shift ;;
  esac
done

# ─── Pre-flight checks ───
log "Checking Python version..."
if ! command -v python3 &> /dev/null; then
  err "Python3 not found. Install Python 3.11+ and retry."
  exit 1
fi

PY_VER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
PY_MAJOR=$(echo "$PY_VER" | cut -d. -f1)
PY_MINOR=$(echo "$PY_VER" | cut -d. -f2)

if [[ "$PY_MAJOR" -lt 3 || ("$PY_MAJOR" -eq 3 && "$PY_MINOR" -lt 11) ]]; then
  err "Python 3.11+ required (found $PY_VER)"
  exit 1
fi
log "Python $PY_VER ✅"

# ─── Virtual environment ───
if [[ ! -d "$HUB_DIR/.venv" ]]; then
  log "Creating virtual environment..."
  python3 -m venv "$HUB_DIR/.venv"
fi
source "$HUB_DIR/.venv/bin/activate"

# ─── Dependencies ───
log "Installing dependencies..."
pip install -q fastapi uvicorn tinydb requests

# ─── Generate tokens ───
if [[ -z "$ADMIN_TOKEN" ]]; then
  ADMIN_TOKEN=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
fi
WRITER_TOKEN=$(python3 -c "import secrets; print(secrets.token_urlsafe(24))")

log "Admin token:  $ADMIN_TOKEN"
log "Writer token: $WRITER_TOKEN"

# ─── Create config ───
cat > "$HUB_DIR/config.json" << EOF
{
  "port": $PORT,
  "host": "0.0.0.0",
  "quality_threshold": 60,
  "max_item_size_bytes": 10240,
  "nodes": {
    "admin-node": {
      "token": "$ADMIN_TOKEN",
      "role": "admin",
      "description": "Admin node (generated by install.sh)"
    },
    "writer-node": {
      "token": "$WRITER_TOKEN",
      "role": "writer",
      "description": "Writer node (generated by install.sh)"
    }
  }
}
EOF
log "config.json created ✅"

# ─── Initialize database ───
mkdir -p "$HUB_DIR/hub_tinydb"
echo '{"knowledge": {}}' > "$HUB_DIR/hub_tinydb/knowledge-index.json"
log "Database initialized ✅"

# ─── Systemd service (Linux only) ───
if command -v systemctl &> /dev/null && [[ "$EUID" -eq 0 ]]; then
  log "Installing systemd service..."
  cat > /etc/systemd/system/knowledge-hub.service << EOF
[Unit]
Description=Knowledge Hub Server
After=network.target

[Service]
Type=simple
WorkingDirectory=$HUB_DIR
ExecStart=$HUB_DIR/.venv/bin/python3 hub_server.py
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable knowledge-hub
  systemctl restart knowledge-hub
  log "systemd service installed and started ✅"
else
  warn "Not running as root or no systemd — using manual start"
  log "To start: cd $HUB_DIR && bash start.sh"
  log "Or:   cd $HUB_DIR && .venv/bin/python3 hub_server.py &"
fi

# ─── Health check ───
sleep 2
if curl -s "http://127.0.0.1:$PORT/health" | grep -q "ok"; then
  log "Health check passed ✅"
else
  warn "Health check pending — server may still be starting"
fi

# ─── Summary ───
echo ""
log "═══════════════════════════════════════════"
log "  Knowledge Hub installed successfully!"
log "═══════════════════════════════════════════"
log ""
log "  Server:   http://127.0.0.1:$PORT"
log "  Health:   curl http://127.0.0.1:$PORT/health"
log "  Admin:    http://<ip>:$PORT/admin?token=$ADMIN_TOKEN"
log "  Dashboard:http://<ip>:$PORT/dashboard?token=$ADMIN_TOKEN"
log ""
log "  Admin token:  $ADMIN_TOKEN"
log "  Writer token: $WRITER_TOKEN"
log ""
log "═══════════════════════════════════════════"
log "  Agent API example:"
log "  curl -X POST http://127.0.0.1:$PORT/admin/node \\"
log "    -H 'Authorization: Bearer $ADMIN_TOKEN' \\"
log "    -H 'Content-Type: application/json' \\"
log "    -d '{\"name\":\"my-agent\",\"role\":\"writer\"}'"
log "═══════════════════════════════════════════"
